app:
  create-default-users: true
  cache:
    initial-capacity: 100
    max-size: 2000
    expire-write-minutes: 5
    expire-access-minutes: 5

spring:
  application:
    name: inventoryCRM
  profiles:
    default: dev
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_crm?serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql

jwt:
  secret: "aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789+/ab=="
  # 1 day
  expiration: 86400000
  # 7 days
  refresh-expiration: 604800000
  issuer: inventory-crm
  audience: crm-users
  token-prefix: Bearer
  token-header: Authorization

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    api-docs:
      path: /v3/api-docs
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.boot.devtools: TRACE
    org.springframework.boot.devtools.restart: DEBUG
