spring:
  cloud:
    nacos:
      serverAddr: ${NACOS_SERVER_ADDR:}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        enabled: ${NACOS_ENABLED:false}
  config:
    import:
      - optional:nacos:dev.yml?refreshEnabled=false&group=DEFAULT_GROUP
